include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - "**/*.config.dart"
    - "lib/generated/**"
    - "lib/l10n/**"
    - ".dart_tool/**"
    - "build/**"

  errors:
    missing_required_param: error
    unused_import: warning
    dead_code: info

  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    one_member_abstracts: false
    public_member_api_docs: false
